/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * A component for displaying a person's name
     */
    interface MyComponent {
        /**
          * The first name, which is required
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name, defaults to "Unknown"
         */
        "middle": string;
        /**
          * A suffix, for titles like "PhD" and "MBA"
          * @deprecated
         */
        "suffix": string;
    }
}
declare global {
    /**
     * A component for displaying a person's name
     */
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * A component for displaying a person's name
     */
    interface MyComponent {
        /**
          * The first name, which is required
         */
        "first": string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name, defaults to "Unknown"
         */
        "middle"?: string;
        /**
          * A suffix, for titles like "PhD" and "MBA"
          * @deprecated
         */
        "suffix"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A component for displaying a person's name
             */
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
