/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * A component for displaying a person's name
     */
    interface MyComponent {
        /**
          * The first name, which is required
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name, defaults to "Unknown"
         */
        "middle": string;
        /**
          * A suffix, for titles like "PhD" and "MBA"
          * @deprecated
         */
        "suffix": string;
    }
    /**
     * An example using Shadow Parts.
     * The 'label' part is declared in the component-level JSDoc using "@part NAME - DESCRIPTION".
     */
    interface ShadowParts {
    }
    interface SlotExample {
    }
}
declare global {
    /**
     * A component for displaying a person's name
     */
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    /**
     * An example using Shadow Parts.
     * The 'label' part is declared in the component-level JSDoc using "@part NAME - DESCRIPTION".
     */
    interface HTMLShadowPartsElement extends Components.ShadowParts, HTMLStencilElement {
    }
    var HTMLShadowPartsElement: {
        prototype: HTMLShadowPartsElement;
        new (): HTMLShadowPartsElement;
    };
    interface HTMLSlotExampleElement extends Components.SlotExample, HTMLStencilElement {
    }
    var HTMLSlotExampleElement: {
        prototype: HTMLSlotExampleElement;
        new (): HTMLSlotExampleElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "shadow-parts": HTMLShadowPartsElement;
        "slot-example": HTMLSlotExampleElement;
    }
}
declare namespace LocalJSX {
    /**
     * A component for displaying a person's name
     */
    interface MyComponent {
        /**
          * The first name, which is required
         */
        "first": string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name, defaults to "Unknown"
         */
        "middle"?: string;
        /**
          * A suffix, for titles like "PhD" and "MBA"
          * @deprecated
         */
        "suffix"?: string;
    }
    /**
     * An example using Shadow Parts.
     * The 'label' part is declared in the component-level JSDoc using "@part NAME - DESCRIPTION".
     */
    interface ShadowParts {
    }
    interface SlotExample {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "shadow-parts": ShadowParts;
        "slot-example": SlotExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A component for displaying a person's name
             */
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            /**
             * An example using Shadow Parts.
             * The 'label' part is declared in the component-level JSDoc using "@part NAME - DESCRIPTION".
             */
            "shadow-parts": LocalJSX.ShadowParts & JSXBase.HTMLAttributes<HTMLShadowPartsElement>;
            "slot-example": LocalJSX.SlotExample & JSXBase.HTMLAttributes<HTMLSlotExampleElement>;
        }
    }
}
